# docker-compose.yml
version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - '.:/app'
